version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    # Add steps to the job
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - persist_to_workspace:
          root: .
          paths:
            - gradle

  regressionTests:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: swaggerapi/petstore3:unstable
    environment:
      ENV: circleci
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - run:
                name: Regression API Tests
                command: gradle regressionTest
                when: always
            - store_test_results:
                path: reports
            - store_artifacts:
                path: reports